### ISSUE TITLE
Unable to build 9.6-1.5 dockerfile

### ISSUE THREAD

**Issue by zgrannan** [clkao/docker-postgres-plv8#26]
I am trying to make a build that uses Postgres version `9.6.3` and plv8 version `1.5.3` based on the `9.6-1.5` Dockerfile (on Docker Hub the Docker image has Postgres `9.6.2`). However, I wasn't able to rebuild the image locally. The error when running `docker build --no-cache .` is:
```________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/gyp.git /tmp/build/plv8-1.5.3/build/v8/build/_gclient_gyp_AEDxVp' in '/tmp/build/plv8-1.5.3/build'
[0:00:00] Cloning into '/tmp/build/plv8-1.5.3/build/v8/build/_gclient_gyp_AEDxVp'...
[0:00:00] Receiving objects:   0% (1/17946)   
[0:00:00] Receiving objects:  10% (1795/17946)   
[0:00:01] remote: Total 17946 (delta 12666), reused 17946 (delta 12666)        
[0:00:01] Receiving objects: 100% (17946/17946), 3.94 MiB | 7.84 MiB/s   
[0:00:01] Resolving deltas:   0% (0/12666)   
[0:00:01] Resolving deltas:  11% (1433/12666)   
[0:00:02] Resolving deltas: 100% (12666/12666)   
[0:00:02] Checking connectivity... done.
[0:00:02] Checked out d174d75bf69c682cb62af9187879e01513b35e52 to a detached HEAD. Before making any commits
in this repo, you should use 'git checkout <branch>' to switch to
an existing branch or use 'git checkout origin -b <branch>' to
create a new branch for your work.
[0:00:02]
----------------------------------------
Traceback (most recent call last):
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient.py", line 2618, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient.py", line 2604, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient.py", line 2359, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient.py", line 1458, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_utils.py", line 1055, in run
    self.item.run(*self.args, **self.kwargs)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient.py", line 891, in run
    self.ParseDepsFile()
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient.py", line 690, in ParseDepsFile
    gclient_eval.Exec(deps_content, global_scope, local_scope, filepath)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 209, in Exec
    _visit_in_module(stmt)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 193, in _visit_in_module
    value = _gclient_eval(node.value, global_scope, filename=filename)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 173, in _gclient_eval
    return _convert(node_or_string)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 146, in _convert
    for k, v in zip(node.keys, node.values))
  File "/usr/lib/python2.7/collections.py", line 52, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 566, in update
    for key, value in other:
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 146, in <genexpr>
    for k, v in zip(node.keys, node.values))
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 146, in _convert
    for k, v in zip(node.keys, node.values))
  File "/usr/lib/python2.7/collections.py", line 52, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 566, in update
    for key, value in other:
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 146, in <genexpr>
    for k, v in zip(node.keys, node.values))
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 165, in _convert
    return _convert(node.left) + _convert(node.right)
  File "/tmp/build/plv8-1.5.3/build/depot_tools/gclient_eval.py", line 167, in _convert
    return _convert(node.left) % _convert(node.right)
TypeError: not all arguments converted during string formatting
make[1]: *** [build/v8-git-mirror-4.3.66] Error 1
Makefile.v8:31: recipe for target 'build/v8-git-mirror-4.3.66' failed
make[1]: Leaving directory '/tmp/build/plv8-1.5.3'
Makefile:145: recipe for target 'static' failed
make: *** [static] Error 2
```

The full output of the `docker build` command is available here: https://gist.github.com/zgrannan/7d3eb260ff6e186059e30560ab30cb3a

I'm not sure immediately what the cause of this error is. I might take a look into fixing it later but if someone has a chance to take a look at it that would be great! And thanks @clkao for making this Dockerfile.

**Comment by ruimarinho** [comment]
Fixed by https://github.com/clkao/docker-postgres-plv8/pull/29.
